version: '3.7'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cookpad

  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    command: [ "yarn", "start:dev" ]

volumes:
  node_modules:
  postgres:
